# Generated by Django 5.2.8 on 2025-12-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailotp_attempts_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_via',
            field=models.CharField(choices=[('emai', 'Email'), ('sms', 'SMS')], default='email', max_length=15),
        ),
    ]
