# Generated by Django 5.2.8 on 2025-12-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_is_verified_customuser_otp_via'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp_via',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=15),
        ),
    ]
